// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:1673

#include "MultMatrizI.h"

// Implementation skeleton constructor
MultMatriz_i::MultMatriz_i (void)
{
}

// Implementation skeleton destructor
MultMatriz_i::~MultMatriz_i (void)
{
}

::CORBA::Float MultMatriz_i::mult (
  ::CORBA::Float a,
  ::CORBA::Float b)
{
  // Add your implementation here
  printf("a = %f & b = %f", a, b);

  return a*b;
}

